language: android
jdk: oraclejdk8
group: deprecated-2017Q4
install:
- sudo apt-get install -y ant
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.3
  - extra
  - android-25
  - android-19
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
before_install:
- yes | sdkmanager "build-tools;28.0.3" "platforms;android-28"
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
script:
- ant build
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: IXErpyQwVf5YRNC9rTU3L3+KaDBI+sgK6VnDJcqUnIzfxjjA29MlrLkZLSENgukLAkwmWik1zL1fqVtEnl7OB6/c9R9dQwkZi8sIgqE0HsZOtst6yP9LHyAWZA4kDKoRpzS23nL6UnvmcJWhc/klngmNWYSuT3GLcaMr0D23HAqSRFBc+iY4YjNcUlj2akm+Hz4LsnQMgSh+otixbx00B+F89b8OnxVxuxfzInxlrSAEJbwkEY8TIIQFsiaqeGuku7rMiZJCoH0TbUVKCUwAuR/AxT1Vapjj6GfQMhB9NEsydp8K3hoiQI5wyNiYMYroxypqHd60f0NcLxcpxDYsSiwZ1zxIPaf8ROu0mVk7IBGNgAnIN1neGUFIEo2vpjh1EzHlVMqQsHM5+X16jdGlIGXZ/eJVkzH4SCeqQvDtRMokJh2kGwcNHzf450bs+YeYuQvhZbq85No4l2fNfrFtFF228KKgUv0Zp2hUYbUpvBM2FrFFcYocJTe/eLNrT19OsMn21WpYD0Xy5b1xGuqGNzs5Nom1pwxakn9hg+96QPD5YsT4svrcwWOo7jzgsUv+DH5QHeBkECDBl7JA+IbBpht8E31xpp8hYyFmSK3CyWvrxqY6Ghls2gV+HHHgbw1A/bMdSvbVHvkd2KSB8JizQY2qvxX/rPHhpQIfHBVUcKk=
  file:
    - bin/bundle.jar
    - bin/uiautomator-stub.jar
  on:
    repo: openatx/android-uiautomator-jsonrpcserver
    tags: true
